### ISSUE TITLE
Improve UI and Functionality of Extracted Shorelines on the map

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#103]
- [x] Add a button to delete extracted shorelines from the map
- [ ] Add UI that allows users to choose how many extracted shorelines they want loaded on
- [ ] Only allow a single selected ROI to have their shorelines loaded on the map
- [ ] If multiple ROI are selected then only the first one in the set has their shorelines loaded
- [ ] Show the satellite and the year, month, day the shoreline was extracted

**Comment by dbuscombe-usgs** [comment]
This is now partially implemented and the rest could be v2?
