### ISSUE TITLE
Generating ROIs after loading ROIs from file causes ROIs from file to vanish from map

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#107]
## Steps to Replicate
1. Load ROI from geojson file (not config file)
2. Draw a bounding box around the ROI
3. Click generate ROI
Result: Original ROI loaded on the map vanishes

**Comment by dbuscombe-usgs** [comment]
Is this still an issue?

**Comment by 2320sharon** [comment]
This is still an issue, but I don't think its a major bug. At some point I'll try to fix this. For now it just means that users can either load from file or generate ROIs but not both.

**Comment by 2320sharon** [comment]
This issue is part of #142 now
