### ISSUE TITLE
SDS classifier and numpy ImportError

### ISSUE THREAD

**Issue by edlazarus** [Doodleverse/CoastSeg#114]
Hello, CoastSeg team –

I've followed your (excellent) instructions for installation and got as far as running the 'SDS_coastsat_classifier' notebook. But in importing 'coastseg' something is breaking down (at kernel [2], line 4). For what it's worth, I cleaned my conda envs and the conda coastseg env is active when I get the error (appended below).

I've attached a coastseg_deps.txt, as requested.

I'm running macOS High Sierra v10.13.6 – browser is Chrome (v.111.0.5563.64).

Again, install was all fine.

Very grateful for any & all recommendations.

– Eli

Here is the error I get (in full):

RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 4
      2 # Local Imports
      3 import coastseg
----> 4 from coastseg import coastseg_map
      5 from coastseg import coastseg_logs #must be the first module loaded to create logs folder
      7 # External Imports

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/coastseg/coastseg_map.py:9
      6 from typing import Optional, Union
      7 from collections import defaultdict
----> 9 from coastseg.bbox import Bounding_Box
     10 from coastseg import common
     11 from coastseg import factory

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/coastseg/bbox.py:7
      5 # Internal dependencies imports
      6 from .exceptions import BboxTooLargeError, BboxTooSmallError
----> 7 from coastseg.common import remove_z_axis
      9 # External dependencies imports
     10 import geopandas as gpd

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/coastseg/common.py:20
     18 import requests
     19 from area import area
---> 20 import geopandas as gpd
     21 import numpy as np
     22 import geojson

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/geopandas/__init__.py:1
----> 1 from geopandas._config import options  # noqa
      3 from geopandas.geoseries import GeoSeries  # noqa
      4 from geopandas.geodataframe import GeoDataFrame  # noqa

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/geopandas/_config.py:109
    102     import geopandas._compat as compat
    104     compat.set_use_pygeos(value)
    107 use_pygeos = Option(
    108     key="use_pygeos",
--> 109     default_value=_default_use_pygeos(),
    110     doc=(
    111         "Whether to use PyGEOS to speed up spatial operations. The default is True "
    112         "if PyGEOS is installed, and follows the USE_PYGEOS environment variable "
    113         "if set."
    114     ),
    115     validator=_validate_bool,
    116     callback=_callback_use_pygeos,
    117 )
    120 options = Options({"display_precision": display_precision, "use_pygeos": use_pygeos})

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/geopandas/_config.py:95, in _default_use_pygeos()
     94 def _default_use_pygeos():
---> 95     import geopandas._compat as compat
     97     return compat.USE_PYGEOS

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/geopandas/_compat.py:10
      8 import pandas as pd
      9 import pyproj
---> 10 import shapely
     11 import shapely.geos
     14 # -----------------------------------------------------------------------------
     15 # pandas compat
     16 # -----------------------------------------------------------------------------

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/shapely/__init__.py:1
----> 1 from .lib import GEOSException  # NOQA
      2 from .lib import Geometry  # NOQA
      3 from .lib import geos_version, geos_version_string  # NOQA

ImportError: numpy.core.multiarray failed to import

**Comment by 2320sharon** [comment]
Hi Eli,
Thank you for using CoastSeg and for reporting this issue. Thank you for stating the OS you're using as well as the full error message. This error message make me believe geopandas failed to successfully install. One quick solution you could try is upgrading numpy which might  fix this problem:
```
conda activate coastseg
conda update numpy
```
If this solution doesn't work let me know and I'll see if I can help you debug this error.
Thank you for your time and patience.

**Comment by edlazarus** [comment]
Thank you, Sharon, for your speedy reply –

I'm betting I'm not in the correct directory when I run the 'update' command, because I see this (uos-... is my machine; edl... is me my user handle on it):

(base) uos-15366:~ edl1e16$ conda activate coastseg
(coastseg) uos-15366:~ edl1e16$ conda update numpy

PackageNotInstalledError: Package is not installed in prefix.
  prefix: //anaconda3/envs/coastseg
  package name: numpy

**Comment by edlazarus** [comment]
Sorry, team – I thought I'd attache the conda list in my initial query – but I don't see it!

Here it is:
[coastseg_deps.txt](https://github.com/SatelliteShorelines/CoastSeg/files/11021673/coastseg_deps.txt)

**Comment by 2320sharon** [comment]
Does the terminal you're running these commands in show that the conda environment has been activated?

**Comment by 2320sharon** [comment]
Ah, I see conda update numpy wouldn't work because numpy as installed with pypi

**Comment by edlazarus** [comment]
Yes – that's the (coastseg) in parentheses...

**Comment by 2320sharon** [comment]
Thank you for sharing the list of conda packages. I was digging through the installed packages and it seems the version of numpy installed in your coastseg environment is a bit old `numpy=1.19.5` compared to the newest version of numpy available `numpy=1.24.2`. Do you think you can try running this command in your coastseg environment

```
conda activate coastseg # if you haven't already activated the coastseg environment
pip install numpy==1.24.2
```

**Comment by edlazarus** [comment]
Done! I'm in. Thank you both – really excited to work with CoastSeg.

**Comment by 2320sharon** [comment]
Yay! I'm happy that worked! Thanks for trying coastseg!

**Comment by edlazarus** [comment]
Hello, team –

New one for you @2320sharon: I installed CoastSeg 0.0.48

Got the same error about numpy, as above in this thread, so I installed numpy==1.24.2 as above. (Note that numpy==1.19.5 appears to be the version that CoastSeg pulls when it downloads.)

This time my terminal informed me of this:

"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.6.5 requires numpy~=1.19.2, but you have numpy 1.24.2 which is incompatible.
coastsat-package 0.1.5 requires numpy<1.23.0, but you have numpy 1.24.2 which is incompatible."

I'm going to try a previous version of numpy that splits the difference, and see if that patches the problem for now...

Cheers!

Eli

**Comment by 2320sharon** [comment]
Hello again Eli,
Thank you for reporting these bugs and for debugging a bit for us. I bellieve I should be able to update coastsat_package to use a newer version of numpy. After I investigate this further I'll update you on this thread.

Good to know it works well enough on `numpy==1.20.0`

**Comment by edlazarus** [comment]
Apologies if I'm being annoying! I know you're busy...

Thanks for helping troubleshoot.

**Comment by 2320sharon** [comment]
Well that was fast, it appears that `coastsat_package` requires `numpy<1.23.0`. All I need to do is figure out why I made it require `numpy<1.23.0` and then get rid of the restriction and we are golden.

No need to apologize, you're actually helping us build a better coastseg by finding these tricky bugs. Thank you!

**Comment by 2320sharon** [comment]
Good news! I was able to remove the `numpy<1.23.0` from `coastsat_package`.
Do you think you try running
`pip install coastsat-package==0.1.6`

**Comment by edlazarus** [comment]
Running `coastseg==0.0.50`

Still fails with same import error pasted at the top of this Issue, even with `coastsat-package==0.1.6`

I'll install numpy==1.20.0 again for now!

**Comment by edlazarus** [comment]
Apologies, @2320sharon –

I started running into strange errors at the shoreline extraction step (basically empty csv files at the end of long computing times). To reset myself and see how everything now works out of the gates, I cleaned `conda`, reinstalled `coastseg`, and updated numpy (within the environment) – new error is here:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 4
      2 # Local Imports
      3 import coastseg
----> 4 from coastseg import coastseg_map
      5 from coastseg import coastseg_logs #must be the first module loaded to create logs folder
      7 # External Imports

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/coastseg/coastseg_map.py:11
      9 from coastseg.bbox import Bounding_Box
     10 from coastseg import common
---> 11 from coastseg import factory
     12 from coastseg.shoreline import Shoreline
     13 from coastseg.transects import Transects

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/coastseg/factory.py:8
      6 from coastseg.shoreline import Shoreline
      7 from coastseg.transects import Transects
----> 8 from coastseg.roi import ROI
      9 from coastseg import exception_handler
     11 logger = logging.getLogger(__name__)

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/coastseg/roi.py:16
     12 from shapely import geometry
     13 from ipyleaflet import GeoJSON
---> 16 from coastseg.extracted_shoreline import Extracted_Shoreline
     18 logger = logging.getLogger(__name__)
     21 class ROI:

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/coastseg/extracted_shoreline.py:24
     21 from matplotlib.pyplot import get_cmap
     22 from matplotlib.colors import rgb2hex
---> 24 from coastsat import SDS_tools
     25 from coastsat import SDS_shoreline
     26 from coastsat import SDS_preprocess

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/coastsat/SDS_tools.py:19
     17 from shapely import geometry
     18 import skimage.transform as transform
---> 19 from astropy.convolution import convolve
     20 import pytz
     21 from datetime import datetime, timedelta

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/convolution/__init__.py:4
      1 # Licensed under a 3-clause BSD style license - see LICENSE.rst
----> 4 from .convolve import (convolve, convolve_fft, convolve_models,
      5                        convolve_models_fft, interpolate_replace_nans)
      6 from .core import *
      7 from .kernels import *

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/convolution/convolve.py:12
      9 from numpy.ctypeslib import load_library, ndpointer
     11 from astropy import units as u
---> 12 from astropy.modeling.convolution import Convolution
     13 from astropy.modeling.core import SPECIAL_OPERATORS, CompoundModel
     14 from astropy.nddata import support_nddata

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/modeling/__init__.py:10
      1 # Licensed under a 3-clause BSD style license - see LICENSE.rst
      3 """
      4 This subpackage provides a framework for representing models and
      5 performing model evaluation and fitting. It supports 1D and 2D models
      6 and fitting with parameter constraints. It has some predefined models
      7 and fitting routines.
      8 """
---> 10 from . import fitting, models  # noqa: F401, F403
     11 from .core import *  # noqa: F401, F403
     12 from .parameters import *  # noqa: F401, F403

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/modeling/fitting.py:39
     36 from astropy.utils.exceptions import AstropyUserWarning
     38 from .optimizers import DEFAULT_ACC, DEFAULT_EPS, DEFAULT_MAXITER, SLSQP, Simplex
---> 39 from .spline import (  # noqa: F401
     40     SplineExactKnotsFitter, SplineInterpolateFitter, SplineSmoothingFitter, SplineSplrepFitter)
     41 from .statistic import leastsquare
     42 from .utils import _combine_equivalency_dict, poly_map_domain

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/modeling/spline.py:15
     12 from astropy.utils import isiterable
     13 from astropy.utils.exceptions import AstropyUserWarning
---> 15 from .core import FittableModel, ModelDefinitionError
     16 from .parameters import Parameter
     18 __all__ = ['Spline1D', 'SplineInterpolateFitter', 'SplineSmoothingFitter',
     19            'SplineExactKnotsFitter', 'SplineSplrepFitter']

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/modeling/core.py:29
     25 from itertools import chain
     27 import numpy as np
---> 29 from astropy.nddata.utils import add_array, extract_array
     30 from astropy.table import Table
     31 from astropy.units import Quantity, UnitsError, dimensionless_unscaled

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/nddata/__init__.py:11
      1 # Licensed under a 3-clause BSD style license - see LICENSE.rst
      3 """
      4 The `astropy.nddata` subpackage provides the `~astropy.nddata.NDData`
      5 class and related tools to manage n-dimensional array-based data (e.g.
   (...)
      8 be easily provided by a single array.
      9 """
---> 11 from .nddata import *
     12 from .nddata_base import *
     13 from .nddata_withmixins import *

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/nddata/nddata.py:13
     11 from astropy.units import Unit, Quantity
     12 from astropy.utils.metadata import MetaData
---> 13 from astropy.wcs.wcsapi import (BaseLowLevelWCS, BaseHighLevelWCS,
     14                                 SlicedLowLevelWCS, HighLevelWCSWrapper)
     16 __all__ = ['NDData']
     18 _meta_doc = """`dict`-like : Additional meta information about the dataset."""

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/wcs/__init__.py:26
      1 # Licensed under a 3-clause BSD style license - see LICENSE.rst
      2 """
      3 .. _wcslib: https://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/index.html
      4 .. _distortion paper: https://www.atnf.csiro.au/people/mcalabre/WCS/dcs_20040422.pdf
   (...)
     23 a standard pipeline.
     24 """
---> 26 from .wcs import *
     27 from .wcs import InvalidTabularParametersError  # just for docs
     28 from . import utils

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/wcs/wcs.py:57
     54 from astropy.utils.decorators import deprecated_renamed_argument
     56 # Mix-in class that provides the APE 14 API
---> 57 from .wcsapi.fitswcs import FITSWCSAPIMixin, SlicedFITSWCS
     59 __all__ = ['FITSFixedWarning', 'WCS', 'find_all_wcs',
     60            'DistortionLookupTable', 'Sip', 'Tabprm', 'Wcsprm', 'Auxprm',
     61            'Celprm', 'Prjprm', 'Wtbarr', 'WCSBase', 'validate', 'WcsError',
   (...)
     66            'NonseparableSubimageCoordinateSystemError',
     67            'NoWcsKeywordsFoundError', 'InvalidTabularParametersError']
     70 __doctest_skip__ = ['WCS.all_world2pix']

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/wcs/wcsapi/fitswcs.py:11
      8 import numpy as np
     10 from astropy import units as u
---> 11 from astropy.coordinates import SpectralCoord, Galactic, ICRS
     12 from astropy.coordinates.spectral_coordinate import update_differentials_to_match, attach_zero_velocities
     13 from astropy.utils.exceptions import AstropyUserWarning

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/coordinates/__init__.py:16
     14 from .earth import *
     15 from .transformations import *
---> 16 from .builtin_frames import *
     17 from .name_resolve import *
     18 from .matching import *

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/coordinates/builtin_frames/__init__.py:29
     27 from .baseradec import BaseRADecFrame
     28 from .icrs import ICRS
---> 29 from .fk5 import FK5
     30 from .fk4 import FK4, FK4NoETerms
     31 from .galactic import Galactic

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/coordinates/builtin_frames/fk5.py:11
      8 from astropy.coordinates import earth_orientation as earth
     10 from .baseradec import BaseRADecFrame, doc_components
---> 11 from .utils import EQUINOX_J2000
     13 __all__ = ['FK5']
     16 doc_footer = """
     17     Other parameters
     18     ----------------
     19     equinox : `~astropy.time.Time`
     20         The equinox of this frame.
     21 """

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/coordinates/builtin_frames/utils.py:16
     14 from astropy.time import Time
     15 from astropy.coordinates.earth import EarthLocation
---> 16 from astropy.utils import iers
     17 from astropy.utils.exceptions import AstropyWarning
     18 from ..representation import CartesianDifferential

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/utils/iers/__init__.py:2
----> 2 from .iers import *

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/utils/iers/iers.py:23
     21 from astropy import config as _config
     22 from astropy import units as u
---> 23 from astropy.table import QTable, MaskedColumn
     24 from astropy.utils.data import (get_pkg_data_filename, clear_download_cache,
     25                                 is_url_in_cache, get_readable_fileobj)
     26 from astropy.utils.state import ScienceState

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/table/__init__.py:68
     65 with registry.delay_doc_updates(Table):
     66     # Import routines that connect readers/writers to astropy.table
     67     from .jsviewer import JSViewer
---> 68     import astropy.io.ascii.connect
     69     import astropy.io.fits.connect
     70     import astropy.io.misc.connect

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/io/ascii/__init__.py:34
     32 from .cds import Cds
     33 from .mrt import Mrt
---> 34 from .ecsv import Ecsv
     35 from .latex import Latex, AASTex, latexdicts
     36 from .html import HTML

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/io/ascii/ecsv.py:15
     12 import numpy as np
     14 from . import core, basic
---> 15 from astropy.table import meta, serialize
     16 from astropy.utils.data_info import serialize_context_as
     17 from astropy.utils.exceptions import AstropyUserWarning

File //anaconda3/envs/coastseg/lib/python3.9/site-packages/astropy/table/meta.py:7
      4 from collections import OrderedDict
      6 import numpy as np
----> 7 import yaml
      9 __all__ = ['get_header_from_yaml', 'get_yaml_from_header', 'get_yaml_from_table']
     12 class ColumnOrderList(list):

ModuleNotFoundError: No module named 'yaml'
​
Any insights from what you see here?

**Comment by 2320sharon** [comment]
Thank you for trying `coastsat-package 0.1.6` I'll see if I can figure  out why numpy isn't installing the correct version. I'll keep you updated with my progress
