### ISSUE TITLE
Move this repo back to the Doodleverse?

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#116]
@kvos I think our original intention for the SatelliteShorelines repo has changed, so it may make sense to move CoastSeg back to the Doodleverse org? That might make more sense because of the coastseg and coastsat packages that @2320sharon has built, plus the integration with the Zoo models, and the planned departures from the CoastSat workflow? Eventually, CoastSeg will have to become official USGS software, and we'd migrate from github to gitlab.

I originally thought that this org would be the home for all the various toolboxes contributing to the SDS benchmark. Do you still plan to move CoastSat and associated toolboxes here, and encourage all SDS benchmark submissions to host their codes here, or at least version the codes that contributed to the benchmark? If not, perhaps we should re-evaluate a home for CoastSeg?

**Comment by kvos** [comment]
@dbuscombe-usgs , yes I think it's better to move CoastSeg back to Doodleverse as nobody (including me) has contributed their toolbox to the SatelliteShorelines organisation. I encouraged participants to include a copy of their code in SDS_Benchmark but there is only a CoastSat copy and Mao's algorithm. My opinion on this one is that it's probably good to use SatelliteShorelines for new collaborative projects that start directly under the org, while existing projects may stay where they are. No worries if you want to move CoastSeg back, makes sense to keep it together with the suite of tools (Gym, Zoo, Doodle) that you, Sharon and others have been developing.

**Comment by dbuscombe-usgs** [comment]
Ok thanks for the input @2320sharon let's plan on doing this next week and let's hope we don't break anything!

**Comment by 2320sharon** [comment]
@dbuscombe-usgs do we want to try moving it this Wednesday?

**Comment by dbuscombe-usgs** [comment]
Thursday

**Comment by dbuscombe-usgs** [comment]
Done. Thanks @2320sharon
