### ISSUE TITLE
Very (very) long computing time for transects

### ISSUE THREAD

**Issue by edlazarus** [Doodleverse/CoastSeg#119]
Hello, team –

Just wondering if you had any idea why the "Computing cross distance transects" step takes as long as it does, even for ~20 transects. Even with a 1k ROI, to minimise the calculation lift, the "computing" stage seems to take ages. (My current calc is now well over 2 hrs and counting.) In this case I'm drawing on 1896 images (L5, L7, L8 & L9), which will yield ~550 shoreline positions 1984–2022.

I happen to be looking at a square of North Carolina, but this kind of extended calc time is typical of all of the ROIs I've tried. Seems to be something deep in the calculation step. Hard to imagine the size of the dataframe is too much for the engine to handle. Curious!

Cheers –

Eli

**Comment by 2320sharon** [comment]
Hi again Eli,
Thanks for bringing up this issue. I'll dig into the cause of the slowdown more and keep you updated on what I discover.

 What I can tell you right now is that its not the number of transects  that's the problem but rather the number of images that's likely the cause of the slowdown. I don't know how many shorelines you were able to extract but for this many images you likely have somewhere around 1000ish extracted shorelines. The code that computes the extracted shoreline and transect intersections is the [compute_intersection_QC from coastsat ](https://github.com/2320sharon/coastsat_package/blob/master/src/coastsat/SDS_transects.py#:~:text=def%20compute_intersection_QC(output%2C%20transects%2C%20settings)%3A)and  runs some nested loops it might be why this is taking so long. We are hoping to speed up some of these slow workflows and if you have any suggestions let us know.

**Comment by edlazarus** [comment]
Thanks, @2320sharon – I think I'm in hour 5+ now? The run may be functionally dead – I might need to reload the config and try again. But nested loops sounds like a culprit – ha!

**Comment by dbuscombe-usgs** [comment]
Still looking into this. This might now be solved due to recent changes. Going forward, we have plans to 

1. remove bad 2d shorelines, so there will be fewer shorelines to map to transects
2. looking into performance tricks on existing code
3. looking into switching to dask to help parallelize workflows

**Comment by 2320sharon** [comment]
@CameronBodine good news the bug has finally been fixed. Turns out there was a single line that would get incredibly slow when there were 100 hundreds of shorelines. Everything should be working correctly in version 0.0.70
`pip install coastseg==0.0.70`. Thank you again for finding this bug
