### ISSUE TITLE
US slope database

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#134]
It is useful to have a database of known beach slopes for US beaches. Some regions may have a more accurate slope from a survey measurement. Other regions may be able to use CoastSat.slope. Some regions may be too steep or have too small a tidal range for CoastSat.slope to work

- [x] make data from https://coastal.er.usgs.gov/data-release/doi-F7GF0S0Z/ as geojson files
- [x] add slope data from California
- [x] add slope data from Australia
- [x] add slope data from Hawaii
- [x] add slope data from Japan
- [x] add slope data from Chile
- [x] add slope data from Peru
- [x] add slope data from NZ
- [X] make these geojson accessible to the user in CoastSeg
- [x] make a map of TR/tanβ, and highlight locations where this value is <10 (where CoastSat.slope not applicable). This can go in the documentation and paper

**Comment by dbuscombe-usgs** [comment]
I have prepared what I think is the easiest way for you @2320sharon to provide the user a beach slope for every transect that we have a beach face slope estimate for.

For each of the existing 24 files (Transects_grid_region_*.geojson files), as well as the existing "id" field, I added new 6 fields:

1. slope: beach face slope, for tidal correction of transect-based data
2. distance: distance in degrees between slope datum location and transect location
3. feature_x: transect location x
4. feature_y: transect location y
5. nearest_x: nearest slope location x
6. nearest_y: nearest slope location y

These values are useful for evaluating the quality of the slope value used based on proximity

I went ahead and published both versions - that way, we have a record of it we can update it as new info becomes available, plus I can add credits to information sources. And, we both worked hard so we should have something to show for it.

https://zenodo.org/record/8187949 -- I hope you like!!

No rush, but it would be cool to eventually integrate the slope-attributed versions of transects

**Comment by dbuscombe-usgs** [comment]
I'll leave this open as a space to discuss implementation. and also as a reminder for me to make a map of TR/tanβ,

**Comment by 2320sharon** [comment]
Thanks for creating these transects that also have the beach slope this is super useful. I was wondering if you wanted to have these new transects replace the existing transects in coastseg?

**Comment by dbuscombe-usgs** [comment]
Ideally, yes. The files with the slopes are a little larger so will load a little slower, but hopefully not much slower. Exposing the 'slope' field would be useful for users to use, but we'll have to discuss the implementation a little more

**Comment by dbuscombe-usgs** [comment]
This task is still open because

- [ ] these new transects should be incorporated into coastseg (eventually)
- [ ] some errors in the endedness of transects (order of sea/land) have been identified and need to be systematically removd
- [ ] I'm still working on the validation plots

**Comment by 2320sharon** [comment]
This issue is related to issue #174

**Comment by dbuscombe-usgs** [comment]
![summary_map_TR_slope_ratio_whole_USA_good4coastsatslope](https://github.com/Doodleverse/CoastSeg/assets/3596509/108a3b0d-7ccf-42c2-aaaf-98dbde59477d)

a (very crap and preliinary) map of locations where we can and cannot use CoastSat.Slope method to estimate beach slope from shoreline time-series. There are a LOT of places of the east coast that won't cut it. West coast is fine

see https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020gl088365 for more details

**Comment by dbuscombe-usgs** [comment]
![summary_map_TR_slope_whole_USA](https://github.com/Doodleverse/CoastSeg/assets/3596509/f373ece1-feea-4672-ab67-cdb968813812)

The above map was created using these inputs

**Comment by 2320sharon** [comment]
As I was doing some final test this morning I realized that the changes to the transects were not backwards compatible so I ended up renaming all the new files to match the old format and testing it again.

Everything should work now
