### ISSUE TITLE
Add new segformer model

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#152]
Please add the new segformer models as an option: https://zenodo.org/record/7933015

For now, I'd like to keep the existing 4-class res-unet model, and add this new 4-class segformer model, which requires the transformers library.

The 2-class models can all be removed for now

**Comment by 2320sharon** [comment]
This issue is directly related to issue #136

**Comment by 2320sharon** [comment]
The new segformer model has been added and the 2 class models have been removed.
These changes are active in `coastseg==0.0.72.dev6`
