### ISSUE TITLE
Shoreline filtering using a mask outlining zone of possible shoreline change

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#161]
I made a dataset that outlines the extent of potential shoreline change, for California and southeast USA Atlantic (FL, GA, SC, NC), in geoJSON format. check it out! https://zenodo.org/record/8174967

It would be very cool if we could use it to filter estimated shorelines that are not in this zone. We can discuss further. Would involve seeing if the shoreline was inside this polygon, and if not, it would be flagged and discarded.

It would remove the problem of impossible shoreline estimates at source. However, it doesn't replace other shoreline filtering efforts, only adds to them. Perhaps this should be the first filter applied.

**Comment by 2320sharon** [comment]
I think we should talk more about this in our meeting on Thursday to solidify an idea of how to implement this. Is the basic idea that we check whether or not the shoreline is within this buffer zone?

**Comment by dbuscombe-usgs** [comment]
Yes that's right. If the extracted shoreline intersects with the mask, throw it out
