### ISSUE TITLE
Feature Request: Allow users to draw bounding box of any shape

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#165]
Sometimes the coastline has irregular shapes that make generating ROIs where you want them difficult. If the user could use the freeform draw tool to draw a bounding box they could generate ROIs where they want, load shorelines where they want, and load transects where they want.

This feature would make the process of extracting shorelines far easier by making the process of generating reference shorelines a piece of cake. 🍰

**Comment by dbuscombe-usgs** [comment]
I added the V2 tag. I think we can work on this later

**Comment by 2320sharon** [comment]
This was added in version 1.1.35
