### ISSUE TITLE
Accessing Planet and Microsoft Planetary computer imagery

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#170]
I have been researching access to imagery from alternative platforms and am using this issue as a placeholder for planning a future effort to integrate at least 3-m Planet imagery for federal researchers with API keys

API keys are accessed from https://account.planet.com/

The basic workflow for https://github.com/planetlabs/notebooks/blob/master/jupyter-notebooks/data-api-tutorials/search_and_download_quickstart.ipynb

Accessing sentinel imagery from planetary is exemplified here: [interactive-sentinel-2-cookbook/notebooks/data-intake-ms-planetary-computer.ipynb at main · ProjectPythia/interactive-sentinel-2-cookbook (github.com)](https://github.com/ProjectPythia/interactive-sentinel-2-cookbook/blob/main/notebooks/data-intake-ms-planetary-computer.ipynb)

**Comment by dbuscombe-usgs** [comment]
There are several steps to implementing use of Planet imagery, including:

1. Planet imagery is not available to all, so we need to figure out a way for users to securely store or input their API key. This has to be done in such a way that the API key is not stored in a file, only in memory in a particular user's session
2. The program should 'grey out' Planet as an available source unless/until the API credentials have been inputted
3. The program will have to be updated to deal with the slightly different metadata and image bands
4. the jpeg creation codes will therefore need to be updated to accomodate Planet imagery
5. testing of the deep learning models on planet imagery, and possibly creating a new set of training data to support this effort
6. one big issue to resolve is image registration. Planet suffers from this quite badly, so [AROSICS](https://danschef.git-pages.gfz-potsdam.de/arosics/doc/installation.html) needs to be fully implemented, which may require a new conda recipe or Docker workflow
7. another issue is cloud masking, which Planet doesnt do by default but we have access to ML-based libraries that do
8. there are probably tens of other little details that we may need to pay attention to as we go

**Comment by 2320sharon** [comment]
Thanks for researching this issue and developing some implementation ideas.

I found that the project geemap has the option to use planet api what it does it uses an environment variable to store the api key. That way we never write the API key to file.
```
# os.environ["PLANET_API_KEY"] = "12345"
```
You can see the full notebook here
https://github.com/gee-community/geemap/blob/cfc9ed8d15436be3a1220e31fb0d775fec69edb8/docs/notebooks/77_planet_imagery.ipynb#L7

**Comment by 2320sharon** [comment]
We are planning on implementing this feature in a new project call Coastseg-Planet
