### ISSUE TITLE
Update docs to remind users to "scroll left" when zoomed to full extent on the map

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#174]
Issue: when a user zooms out far enough, they are confronted with multiple versions of the world map. When a ROI is placed on a 'right-hand world', the pre-existing reference shorelines do not load on the map. They do, however, if a 'left-hand' world is used.

Possible solution 1: Can a limit be imposed on the level of zoom out, in order to prevent the 'multiple worlds' effect? 

Fallback solution 1: Update the docs so users are advised to pan left, and use the left-hand version of the world map?

**Comment by 2320sharon** [comment]
I was hoping that disabling the infinite map was as easy as setting `world_copy_jump=False`, but it seems this parameter is already False and changing it to True or False seems to do nothing...
https://ipyleaflet.readthedocs.io/en/latest/map_and_basemaps/map.html#:~:text=int%2C%20default%2015-,world_copy_jump,-%23

**Comment by dbuscombe-usgs** [comment]
I think we need 
`world_copy_jump = True`

**Comment by dbuscombe-usgs** [comment]
I think that will not prevent the multiple worlds, but perhaps it will allow our vector features to show up on any "right hand" world

**Comment by 2320sharon** [comment]
I'm trying that out right now

**Comment by dbuscombe-usgs** [comment]
Another idea would be to use `fit_bounds` using the extent of the world in the format  [[south, west], [north, east]]

i.e.  [[-90, -180], [90, 180]].

?

**Comment by 2320sharon** [comment]
I tried the fit bounds idea earlier but its basically a glorified zoom to zone. doesn't actually limit the map

**Comment by 2320sharon** [comment]
The good news is the world_copy_jump = True. I scrolled to each side of the world and it worked. I'm gong to test this a few times before I call this issue closed.

**Comment by dbuscombe-usgs** [comment]
Great!

**Comment by 2320sharon** [comment]
Looks like its working. I'm so glad that works.
I'll release this fix as part of `0.0.73dev4`
