### ISSUE TITLE
Stalls on very large downloads

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#178]
I decided to stress-test the image download by defining 18 ROIs in western Alaska, with a 39 year time-period (1984-1-1 to 2023-1-1), and it stalled on ROI 10 out of 18

By the time it stalled, it had downloaded 103,062 images totalling 44.4 GB. So not bad!

![Screenshot from 2023-08-16 19-37-10](https://github.com/Doodleverse/CoastSeg/assets/3596509/f087e27b-3728-4140-b290-ed2ece76922e)

![Screenshot from 2023-08-16 19-37-03](https://github.com/Doodleverse/CoastSeg/assets/3596509/b1cd41c6-c5d9-4c5b-bac2-3b45d7ed080b)

![Screenshot from 2023-08-16 19-36-57](https://github.com/Doodleverse/CoastSeg/assets/3596509/c6aeca5f-5737-4c40-8666-55f875f202ce)

The log is not very informative, but here it is
[log_08-16-23-10_14_10.txt](https://github.com/Doodleverse/CoastSeg/files/12364894/log_08-16-23-10_14_10.txt)

I am on Linux, using coastseg 0.73. Perhaps this is a GEE issue?

**Comment by dbuscombe-usgs** [comment]
Yes, it was quite odd. It just froze, with no error. After several hours I had to kill the kernel.

**Comment by dbuscombe-usgs** [comment]
I had this happen again several times over the past week, on linux on my home network. 

I like to download all ~40 years of imagery all at once

Each time, after a certain number of downloads, it freezes. I have to eventually kill it, because it hangs indefinitely. I will share my log files. I have tried single and multiple ROIs, and also various date ranges.

I'm testing on Windows and not seeing similar issues there

**Comment by 2320sharon** [comment]
Thanks for testing large downloads both on Linux and Windows. 
There's a whole host of reasons the downloads could be hanging on Linux which means this will be a difficult issue to narrow down. Here is my plan for narrowing now the issue.

1. Analyze the log file for clues
2. Update coastsat_package so that it is update to date with all the update to coastsat
3. Analyze the coastsat code and coastseg code to see if something is getting stuck
4. Identify the issue & report back
5. Fix it !

**Comment by 2320sharon** [comment]
To figure out what's causing this stall here is a list of what I'll need
### Necessary Files
- [ ] config geojson file
- [ ] config json file
- [ ] log file
- [ ] Linux version used ( I need to spin up a VM)

### Helpful but Optional Files
- [ ] Screenshot or description of when it stopped

**Comment by dbuscombe-usgs** [comment]
I provided a screenshot and log file. I cant provide a config geojson or config json file because the program doesn't make them

**Comment by 2320sharon** [comment]
# Update
##Context
Yesterday I created a linux VM to test out this bug. I used the config files located in [configs_for_linux.zip](https://github.com/Doodleverse/CoastSeg/files/12796880/configs_for_linux.zip) to download the imagery that failed on the Linux machine Dan used. Below you can see a screenshot that shows the downloads stalled on the second ROI when it was downloading S2 imagery. @dbuscombe-usgs  found this happened consistently when he downloaded S2 imagery with multiple ROI.
![image (1)](https://github.com/Doodleverse/CoastSeg/assets/61564689/953a59ae-2351-4137-bf72-087f1a46eaad)

## Results from My Test
I used the config files mentioned above to download the imagery and it finished successfully. Each ROI has 706 images and both ROIs completed downloading. The downloads did get a little bit slower with time going from 5 seconds per download to 6.5 seconds per download near the end. As I was writing this I realized I was using `coastsat_package` `1.22` which contains upgraded code for downloading S2 imagery which might have fixed the bug that occurred before.

I have a few theories why downloads could be failing:
1. Internet Connectivity Issue
- its possible that when the internet connection becomes unstable sometimes the download will fail causing the `@retry` decorator on the `download_tif` function to run to attempt to re-download the file.
2. Exceptions Being Raised
- There could be exceptions being raised by the coastsat download code that aren't being handled.

## Next Steps
I made upgrades to the `coastsat_package` that should improve error handling for S2 imagery as well as incorporate the new S2 mask. When I released `coastseg` `1.1` I'll re-run this test and see if I get the download error. Then I'll try to improve the error handler for download issues in `coastsat_package`.

**Comment by 2320sharon** [comment]
In today's meeting we decided it would be best if downloads would not all quit if a single download failed due to an exception. This means that we want to modify the logic and coastsat package, so that instead of ceasing all the downloads when a single download fails it will instead

**Comment by 2320sharon** [comment]
This feature has been implemented in `coastsat-package` version 0.1.23. Now downloads will only halt if more than five errors occurred when the download of a single ROI was attempted. 

This feature is available in `coastseg 1.1.1`

`pip install coastsat-package==0.1.23`

For now I will close this issue as I believe it is resolved, but reopen it if this issue continues and I'll dive deeper.
