### ISSUE TITLE
Feature request: option to provide a list of date ranges and scalar offset of +/- days

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#180]
When comparing time-series of SDS and ground-based surveys, which are at discrete time periods, it would be useful to have the ability to only download imagery within certain time ranges. Plus, an ability to specify a scalar number of days that would buffer the start and end days when downloading imagery. This would be set by the user according to the application, but would provide the nearest-in-time available imagery for download near a specified range of dates.

When discussed, a possible solution was to provide a text file or similar that would list the date ranges, and create new time vectors for image downloads. It would be a) optional, and b) mutually exclusive of the other default way of selecting dates

**Comment by dbuscombe-usgs** [comment]
Depending on difficult to implement, this could be V1 or V2.

What would the inputs look like? In this file, I specified 3 separate date ranges in YYYY-MM-DD format, separated by --, and also the number of days to buffer the date range either side. Not sure if that's the best format

[date_ranges.txt](https://github.com/Doodleverse/CoastSeg/files/12372955/date_ranges.txt)

**Comment by 2320sharon** [comment]
This is going to be a big change. This would require large amounts of refactoring. The more I think about this feature the more I realize it requires basically re-building everything. TBH I don't know if this is worth implementing. However, if we switch to xarray this is would be easier I think.

If I had to estimate the amount of effort this would take to implement it would be 3 weeks to maybe a month. The dates impact a lot of stuff.

**Comment by dbuscombe-usgs** [comment]
Thanks for looking into this, and I agree. I think our priority should remain making existing features work better. This would be nice to have, but won't result in better shorelines, just fewer shorelines. 

We'll mark it V2, and reassess in several months

**Comment by 2320sharon** [comment]
I agree we can revisit this later when we've come up with more insight on the problem as well as some new approaches to extracting shorelines

**Comment by 2320sharon** [comment]
In the TCA meeting they mentioned they want to be able to query a list of dates for the ROIs. This change would require changes to the settings to allow a list of dates to be accepted and the download functions to be modified to allow list of dates to be passed. Basically each ROI would need to call the coastsat function `retrieve_images` N times where N is the number of date ranges the user requested.

I estimate this change would take 2 days at least and at most 4 days. The following changes would need to take place

- [ ] the settings UI for dates would need to be modified to accept dates

- [ ] the sessions would need to be able to account for each date in the list

- [ ] any coastsat code that accesses dates may need to be modified

- [ ] a new widget would need to be designed to accept multiple lists
 

- [ ] New tests would need to be written to ensure extract shorelines, correct tides and all other functions still work with the new dates list


Given that this new feature has the potential to impact large portions of coastseg we would recommend users to make multiple sessions with the same ROIs, shorelines, transects, etc. The only thing they should change across settings would be the dates. Then when they've extracted shorelines for all of the dates they can use the upcoming script in #179 to merge the results together.

**Comment by 2320sharon** [comment]
I added a guide on how to use the new script at https://github.com/Doodleverse/CoastSeg/wiki/08.-How-to-Use-Scripts

**Comment by 2320sharon** [comment]
This is now in the wiki https://github.com/Doodleverse/CoastSeg/wiki/07.-How-to-Extract-Shorelines
Its the first Youtube tutorial under the "How to Extract Shorelines" page
