### ISSUE TITLE
Feature Request: Save meta as json instead of pickle

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#184]
Modify the coastsat script to save pickle to save json file instead.

**Comment by 2320sharon** [comment]
In the event this can't be easily modified within coastsat_package, then create a script to do this.

**Comment by dbuscombe-usgs** [comment]
This is related to image registration (and therefore https://github.com/Doodleverse/CoastSeg/issues/133)

The issue is that the georeference accuracy (m) value is in the pkl metadata. This is not human readable and has issues with serialization and backwards compatiable. So it is not easy to get the georeference accuracy out to use it for reporting and AQ/AC

**Comment by 2320sharon** [comment]
After examining the coastsat_package code I have verified that it doesn't ever read from the pickled metadata files, which mean we can safely change it to json without fear of it breaking something else. I've tested saving the data as a json file using the `file_utilities.write_to_json` function and it works great after changing the datetime imports 
```
from datetime import date, datetime
```
I should be able to have this change intregated by next week

**Comment by dbuscombe-usgs** [comment]
Really great. Having all the relevant metadata in json means we can move on image registration. The basic idea is that we want to register the S2 imagery to Landsat imagery.

My basic thinking is to try to adopt the workflow used [here](https://github.com/ydoherty/CoastSat.PlanetScope/blob/cee48dc4cbea80d2f53cdc09970c9cf4e2309bf9/coastsat_ps/preprocess.py#L145) as I detail [here](https://github.com/Doodleverse/CoastSeg/discussions/43#discussioncomment-5930559)

I think it would work on each S2 image by finding the nearest-in-time Landsat image and performing a co-registration, with the Landsat scene being treated as the reference scene. The georeference accuracy (m) value from the json metadata file would be used when assigning a georeference accuracy to each S2 scene, which would be the landsat georef acc and the s2 coreg error summed in quadrature. Then we'd have to come up with a way to write that s2 georef acc back to the json file.

In the coastseg workflow, it would occur after the image downloading, if s2 images had been downloaded. We could either replace each S2 image with the registered image, or preferably, come up with a way to copy the original image into a new filename, then write out the new S2 image to the original filename.

I will try to sketch this out this workflow more fully with code, as my contribution to https://github.com/Doodleverse/CoastSeg/issues/133

**Comment by dbuscombe-usgs** [comment]
We can discuss further. It is not urgent

**Comment by 2320sharon** [comment]
This helps a lot with the image co-registration feature coming down the pipeline.
I think we should be able to rename the un registered S2 imagery by appending "unregistered" to the filenames. That way for most operations we can deal with the registered image.

I'll do a bit of digging into the co-registeration workflow you shared so we can come up with some ideas tommorrow.

**Comment by 2320sharon** [comment]
`Coastsat_package` version  `0.1.18` saves the metadata file as a json instead of a pickle. This issue has been resolved in
 [v1.0.0dev7](https://github.com/Doodleverse/CoastSeg/releases/tag/v1.0.0dev7) and will be officially incorporated in version 1.1.0
