### ISSUE TITLE
change default slope and elevation values for tide correction

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#216]
default beach slope should be 0.02
default elevation should be 0

Please label as follows:

'Beach slope (m/m)'
'Elevation (m, relative M.S.L.)'

Thanks :)

**Comment by 2320sharon** [comment]
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/140764c9-ae19-489b-b6ab-068af09f145a)
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/8ad48a24-6278-4f81-9d5f-23591b43bee1)

**Comment by 2320sharon** [comment]
this feature will be in coastseg 1.1.28
