### ISSUE TITLE
Explore possibility of serving notebooks as Panel apps

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#88]
It would be really nice to explore the possibility of using Panel to make a webapp, using 

`panel serve SDS_coastsat_classifier.ipynb`

What are the current limitations (if any)? Dependency issues? Widgets not rendering properly? other?

**Comment by 2320sharon** [comment]
I'll run some experiments with Panel and see I can get this to work and report back  to you.

**Comment by 2320sharon** [comment]
From my initial experiments months ago, moving to panel does not appear to be a viable option. Instead it would be better to investigate other front ends that don't have the same restrictions as jupyter. It would be fantastic if the front end would allow for multiprocessing unlike jupyter.
